Netflix/karyon

gradle.properties
karyon-admin-web/src/main/java/netflix/adminresources/resources/KaryonWebAdminModule.java
karyon-admin/build.gradle
karyon-admin/src/main/java/netflix/admin/AdminExplorerManager.java
karyon-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java
karyon-archaius/build.gradle
karyon-archaius/src/main/java/netflix/karyon/archaius/ArchaiusBootstrap.java
karyon-archaius/src/main/java/netflix/karyon/archaius/ArchaiusBootstrapModule.java
karyon-core/build.gradle
karyon-eureka/build.gradle
karyon-eureka/src/main/java/netflix/karyon/eureka/KaryonEurekaModule.java
karyon-examples/src/main/java/netflix/karyon/examples/hellonoss/server/rxnetty/MyApplicationRunner.java
karyon-examples/src/main/java/netflix/karyon/examples/hellonoss/server/simple/module/SimpleRunner.java
karyon-examples/src/main/java/netflix/karyon/examples/websockets/WebSocketEchoServer.java
karyon-governator/build.gradle
karyon-governator/src/main/java/netflix/karyon/AbstractKaryonServer.java
karyon-governator/src/main/java/netflix/karyon/Karyon.java
karyon-governator/src/main/java/netflix/karyon/KaryonBootstrap.java
karyon-governator/src/main/java/netflix/karyon/KaryonBootstrapModule.java
karyon-governator/src/main/java/netflix/karyon/KaryonRunner.java
karyon-governator/src/main/java/netflix/karyon/KaryonServerBackedServer.java
karyon-governator/src/main/java/netflix/karyon/MainClassBasedServer.java
karyon-governator/src/main/java/netflix/karyon/RxNettyServerBackedServer.java
karyon-governator/src/main/java/netflix/karyon/ShutdownModule.java
karyon-jersey-blocking/build.gradle
karyon-servo/build.gradle
karyon-servo/src/main/java/netflix/karyon/servo/KaryonServoModule.java

BREAKING: Move away from LifecycleInjectorBuilder and suites in favor of just Bootstrap module. I tried to keep the naming consistent, hence removing references to "suite".

Bump governor, rxnetty and guava versions.

---

karyon-admin/src/main/java/netflix/adminresources/AdminPageRegistry.java
karyon-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java
karyon-admin/src/test/java/netflix/adminresources/AdminResourceTest.java

1. using dynamic configuration (archaius) instead of governator configuration annotation for admin console port, jersey packages
2. admin console port 0 is used for unit test which essentially makes jetty find an unused port to start server. 
3. default admin pages scan path moved to "netflix"

using ephemeral admin port for test

---

karyon-governator/src/main/java/netflix/karyon/KaryonBootstrapModule.java

KaryonBootstrap gets bound in LifecycleInjector with BootStrap module discovery for KaryonBootstrap annotation. Hence removing a double binding from KaryonBootstrapModule to prevent guice bootstrap error

karyon governator 1.3.3 integration fix

---

karyon2-admin-plugins/karyon2-admin-healthcheck-plugin/src/test/java/netflix/adminresources/HealthCheckResourceTest.java
karyon2-admin-web/src/main/java/netflix/adminresources/pages/AdminPageResource.java
karyon2-admin-web/src/test/java/netflix/adminresources/WebAdminTest.java
karyon2-admin/src/main/java/netflix/admin/AdminConfigImpl.java
karyon2-admin/src/main/java/netflix/admin/AdminContainerConfig.java
karyon2-admin/src/main/java/netflix/adminresources/AbstractAdminPageInfo.java
karyon2-admin/src/main/java/netflix/adminresources/AdminPageInfo.java
karyon2-admin/src/main/java/netflix/adminresources/AdminPageRegistry.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java
karyon2-admin/src/test/java/netflix/admin/AdminPageRegistryTest.java
karyon2-admin/src/test/java/netflix/adminresources/AdminResourceTest.java

1. AdminPage plugin can provide a list of guice bindings that a plugin author can create. The modules will be included in the Guice injector that is created as a result of AdminResourceContainer startup routine.
2. AdminResourceContainer defined as a singleton has an instance of AdminPageRegistry that can be accessed with a getter. 
3. AdminResourceContainer allows setting a listenport explicitly. This along with #2 allows for potentially running multiple instances of AdminResourceContainers within a single JVM with a separate AdminPageRegistry associated with each instance.

admin plugin support for additional guice modules

---

karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java

Eureka2 has a dependency on karyon snapshot (something that eureka will need to fix) that references this variable. Since snapshot artifacts are malleable this removal breaks current eureka2 rc.1. Adding it back here for migration backwards compatibility.

Adding back reference to CONTAINER_LISTEN_PORT in AdminResourceContainer for backwards compatibility

---

gradle.properties
karyon2-core/src/main/java/netflix/karyon/health/HealthCheckInvocationStrategy.java
karyon2-core/src/main/java/netflix/karyon/transport/http/RegexUriConstraintKey.java
karyon2-core/src/main/java/netflix/karyon/transport/http/ServletStyleUriConstraintKey.java
karyon2-core/src/main/java/netflix/karyon/transport/http/SimpleUriRouter.java
karyon2-core/src/main/java/netflix/karyon/transport/interceptor/InterceptorExecutor.java
karyon2-core/src/main/java/netflix/karyon/transport/interceptor/KeyEvaluationContext.java
karyon2-core/src/test/java/netflix/karyon/server/interceptor/InterceptorExecutorTest.java
karyon2-core/src/test/java/netflix/karyon/server/interceptor/TestableRequestRouter.java
karyon2-examples/src/main/java/netflix/karyon/examples/hellonoss/server/rxnetty/MyApplicationRunner.java

`InterceptorExecutor` was not adding unsubscribe hooks to the child when there were no interceptors.
- Fixed javadoc errors
- Upgraded rxnetty & eureka versions

Fixes #200 #122

---

karyon2-governator/src/main/java/netflix/karyon/transport/util/HttpContentInputStream.java
karyon2-jersey-blocking/src/main/java/netflix/karyon/jersey/blocking/JerseyBasedRouter.java
karyon2-jersey-blocking/src/main/java/netflix/karyon/jersey/blocking/NettyToJerseyBridge.java
karyon2-jersey-blocking/src/test/java/netflix/karyon/jersey/blocking/JerseyBlockingModule.java
karyon2-jersey-blocking/src/test/java/netflix/karyon/jersey/blocking/JerseyBlockingTest.java
karyon2-jersey-blocking/src/test/java/netflix/karyon/jersey/blocking/JsonReadingResource.java

1. Partial data read in Jersey blocking
2. Memory leak, as the ByteBuf was not released
Unit tests to verify both issues

Fix for: Karyon Jersey Blocking ( partial read + memory leak )

---

gradle.properties
karyon2-eureka/build.gradle

This PR will fix #214 by changing the eureka client version. Currently I updated the version inside gradle.properties and used that variable inside the karyon2-eureka project.

Fixed #214: Changed the Eureka client version to the latest version

---

karyon2-admin/build.gradle
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java

jetty-9 has some backward compatibility issues with respect to its API. This change addresses them as well as the dependency upgrades

upgrading to jetty-9

---

karyon2-admin/build.gradle
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java

Embedding jetty-9 caused conflicts with Tomcat 6 (and a few Tomcat 7 versions) as jetty-9 pulls in servlet 3.1 which gets dropped by tomcat.
Hence going back to jetty-6 based on servlet 2.5

jetty-6 downgrade

---

karyon2-admin-web/src/main/java/netflix/adminresources/pages/AdminPageResource.java
karyon2-admin/src/main/java/netflix/admin/AdminConfigImpl.java
karyon2-admin/src/main/java/netflix/admin/AdminContainerConfig.java
karyon2-admin/src/main/java/netflix/adminresources/AdminPageRegistry.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java

AdminContainerConfig supports shouldIsolateResources(). It creates a separate root injector instead of a child injector to parent application.
Most applications won't need to use this knob. The default behavior is to integrate bindings from parent application injector so they are available in admin resources classes

optional support for full resource isolation

---

karyon2-admin-web/src/main/java/netflix/adminresources/pages/AdminPageResource.java
karyon2-admin-web/src/test/java/netflix/adminresources/WebAdminTest.java

For an invalid viewId - trying to render Viewable results into a 500 with a ton of error logging on service. More frequently it has been the case for /favicon requests that were reported. 
This code changes cleanly returns a 404 if viewId is determined to be invalid
Unit Test is added to cover this issue

404 on bad Viewable request

---

karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/rest/AdminHttpHandler.java

There were two cases where the content-length header would
be incorrect:
1. If multi-byte characters were used in the payload. It was
returning the character length instead of the number of
bytes.
2. If compression was used it was returning the size of the
raw data rather than the compressed size.
This change also makes the charset for the output UTF-8 rather
than using whatever the default is for the jdk.
Quick verification was done on the command line for the compression
use-case to verify the content-length now matches expectations:
```
$ curl -vs 'http://localhost:8077/jars' 2>headers | wc -c; cat headers | grep -i content-length
31192
< Content-length: 31192
$ curl -vs 'http://localhost:8077/jars' -H'Accept-Encoding:gzip' 2>headers | wc -c; cat headers | grep -i content-length
2717
< …
```

3.x: fix content length

---

karyon2-admin/src/main/java/netflix/admin/AdminConfigImpl.java
karyon2-admin/src/main/java/netflix/admin/AdminContainerConfig.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java
karyon2-admin/src/test/java/netflix/adminresources/AdminResourceTest.java
karyon2-admin/src/test/java/netflix/adminresources/AuthFilter.java

config param to introduce additional filters to admin resources.
While it defaults to no different behavior than current state, it provides an extension point to provide extra tomcat filter behavior that is pluggable in karyon2-admin container

Additional filters in karyon2-admin container

---

karyon3-core/src/main/java/com/netflix/karyon/admin/ThreadsAdminResource.java

The goal is to format the stack traces from the threads
admin resource so they can be copy and pasted into common
tools for analyzing them and browsing the code. This change
adds the the file name and formats similar to jstack output.

add file name to thread stack trace

---

karyon3-archaius2/src/main/java/com/netflix/karyon/archaius/ArchaiusKaryonModule.java
karyon3-archaius2/src/main/java/com/netflix/karyon/archaius/admin/ArchaiusPropResource.java
karyon3-core/src/main/java/com/netflix/karyon/Karyon.java
karyon3-log4j2/src/main/java/com/netflix/karyon/log4j/ConsoleAppenderConfigurator.java
karyon3-log4j2/src/main/java/org/apache/logging/log4j/core/ArchaiusLog4J2ConfigurationFactory.java
karyon3-log4j2/src/main/java/org/apache/logging/log4j/core/ConfigListeners.java
karyon3-log4j2/src/test/java/com/netflix/karyon/TestDynamicLogLevels.java

* Make ConsoleAppenderConfigurator configurable via 'karyon.log4j' prefix
* Dynamically update log levels whenever the configuration changes
Misc changes,
* Don't completely fail returning properties in ArchaiusPropResource.  Instead report the errors as the property value
* Allow default application name to be empty

Dynamic Log4J2 log levels

---

karyon3-core/src/main/java/com/netflix/karyon/KaryonAutoContext.java
karyon3-core/src/main/java/com/netflix/karyon/LifecycleInjectorCreator.java
karyon3-core/src/main/java/com/netflix/karyon/conditional/ConditionalOnMissingBinding.java
karyon3-core/src/main/java/com/netflix/karyon/conditional/impl/OnMissingBindingCondition.java
karyon3-core/src/test/java/com/netflix/karyon/conditional/ConditionalOnMissingBindingTest.java

Modify OnMissingBindingCondition to be true IFF an injection point exists but no binding is provided in a module.
ConditionalOnMissingBinding should be used in combination with conditionals such as ConditionalOnProfile instead of ConditionalOnModule to provide a binding if and only if one wasn't already explicitly specified.  This results in an easier to reason behavior when a binding is provided.

Proper implementation of ConditionalOnMissingBinding

---

karyon2-admin/build.gradle

That caused dependency issues.

Remove compile dep to servlet and jetty

---

karyon2-governator/src/main/java/netflix/karyon/AbstractKaryonServer.java
karyon2-governator/src/main/java/netflix/karyon/Karyon.java
karyon2-governator/src/main/java/netflix/karyon/KaryonBootstrap.java
karyon2-governator/src/main/java/netflix/karyon/KaryonBootstrapModule.java
karyon2-governator/src/main/java/netflix/karyon/KaryonRunner.java
karyon2-governator/src/main/java/netflix/karyon/KaryonServer.java
karyon2-governator/src/main/java/netflix/karyon/KaryonServerBackedServer.java
karyon2-governator/src/main/java/netflix/karyon/MainClassBasedServer.java
karyon2-governator/src/main/java/netflix/karyon/RxNettyServerBackedServer.java
karyon2-governator/src/main/java/netflix/karyon/ShutdownModule.java

Karyon2 is no longer a supported project.  We recommend users either use RxNetty (https://github.com/ReactiveX/RxNetty) directly in combination with Governator (https://github.com/Netflix/governator) or other DI frameworks.

Deprecate main entry point classes of Karyon2

---

karyon2-admin/src/main/java/netflix/admin/AdminConfigImpl.java
karyon2-admin/src/main/java/netflix/admin/AdminContainerConfig.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesFilter.java

Properties will be prefixed with 'netflix.admin'.  
For example, WADL for admin resources can be turned off by setting
```
netflix.admin.com.sun.jersey.config.feature.DisableWADL=true
```

Properties to configure jersey under admin resources 
