Netflix/karyon

karyon-admin-web/src/test/java/netflix/adminresources/WebAdminTest.java

admin web resources need to use unused port for starting admin console. Fixing the test class to provide "0" as the requested port in AdminResourcesContainer

admin web resources test using ephemeral port for admin server

---

karyon2-admin-web/src/main/java/netflix/adminresources/resources/JarsInfoResource.java
karyon2-admin-web/src/main/resources/webadmin/jars/index.js

JarsInfoResource is extended to provide full manifest info resources endpoint, but the UI part is still not implemented.

Add more columns to jar info page.

---

karyon2-admin/src/main/java/netflix/adminresources/AdminPageRegistry.java
karyon2-admin/src/test/java/netflix/admin/AdminPageRegistryTest.java

AdminPage annotation that is used to register admin plugins is configurable with defaults in place so it is backwards compatible.

AdminPage Annotation configuration

---

karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java

Making redirect filter available in all context handlers

redirect filter configuration

---

karyon2-admin-plugins/karyon-admin-healthcheck-plugin/build.gradle
karyon2-admin-plugins/karyon-admin-healthcheck-plugin/src/main/java/com/netflix/adminresources/HealthcheckResource.java
karyon2-admin-plugins/karyon-admin-healthcheck-plugin/src/main/java/netflix/adminresources/HealthCheckPlugin.java
karyon2-admin-plugins/karyon-admin-healthcheck-plugin/src/test/java/netflix/adminresources/HealthCheckResourceTest.java
karyon2-admin/src/test/java/netflix/admin/AdminPageRegistryTest.java
settings.gradle

karyon1 healthcheck plugin that can be used with  karyon2-admin framework

karyon1 healthcheck plugin

---

karyon2-admin-web/src/main/java/netflix/adminresources/pages/AdminPageResource.java
karyon2-admin/src/main/java/netflix/admin/AdminExplorerManager.java
karyon2-admin/src/main/java/netflix/admin/GlobalModelContextOverride.java

AdminPageResource is using field injection in order to provide a default constructor

adminPageResource fix for spring initialization

---

karyon2-governator/src/main/java/netflix/karyon/transport/util/HttpContentInputStream.java

This pull request is to start conversation going
```
Per documentation: onNext()
The Observable will not call this method again after it calls either Observer.onCompleted() or 
Observer.onError(java.lang.Throwable).
```
What we see, under the stress conditions, 100s of requests, for no payload requests ( like GET ) we are getting onNext( 0 bytes ), onComplete sometime after we call 
subscriber.onCompleted() and already tiered down and close request stream. This is Jersey Blocking.
Proposed change, ignore 0 byte writes, logically same as no writes ( we will still produce error for non empty writes after stream is closed, as it should) .
It is likely problem somewhere else, but I think this change still benefits the code.

ignore 0 byte writes, to compensate for onNext() call sometime after Observer.onCompleted() 

---

karyon2-admin-web/src/main/java/netflix/adminresources/resources/AllPropsResource.java
karyon2-admin-web/src/main/java/netflix/adminresources/resources/EnvironmentResource.java
karyon2-admin-web/src/main/java/netflix/adminresources/resources/JarsInfoResource.java
karyon2-admin-web/src/main/java/netflix/adminresources/resources/PropertiesHelper.java
karyon2-admin-web/src/main/resources/webadmin/env/index.js
karyon2-admin-web/src/main/resources/webadmin/jars/index.js

* Jars, Env resources updated to be compatible with karyon1 applications.
* All properties json resource added for easy scripting

All properties resource added

---

karyon2-admin/src/main/java/netflix/admin/AdminConfigImpl.java
karyon2-admin/src/main/java/netflix/admin/AdminContainerConfig.java
karyon2-admin/src/main/java/netflix/admin/DefaultGlobalContextOverride.java
karyon2-admin/src/main/java/netflix/admin/GlobalModelContextOverride.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java
karyon2-admin/src/test/java/netflix/adminresources/AdminResourceTest.java

* admin config disable configuration - test added for the same
* DefaultGlobalContextOverride

admin config disable config, tests

---

karyon2-admin/src/main/java/netflix/admin/AdminExplorerManager.java
karyon2-admin/src/main/java/netflix/admin/DefaultRedirectRules.java
karyon2-admin/src/main/java/netflix/admin/RedirectRules.java
karyon2-admin/src/main/java/netflix/adminresources/RedirectFilter.java
karyon2-admin/src/test/java/netflix/adminresources/AdminResourceTest.java

RedirectRules enhanced with a custom rule hook that can be used to run complex redirect logic in addition to a simple table lookup

redirect rules get a custom redirect logic hook

---

gradle.properties
karyon3-archaius2/src/main/java/com/netflix/karyon/archaius/ArchaiusKaryonConfiguration.java
karyon3-core/src/main/java/com/netflix/karyon/DefaultKaryonConfiguration.java
karyon3-examples/src/main/java/com/netflix/karyon/example/rxnetty/HelloWorldRequestHandler.java

Fix polymorphic builder
Add ArcahiusKaryonConfiguration methods to customize archaius
Fix hello world RxNetty routing

Archaius integration improvements

---

.gitignore
karyon-eureka/src/main/java/com/netflix/karyon/server/eureka/AsyncHealthCheckInvocationStrategy.java
karyon-eureka/src/test/java/com/netflix/karyon/server/eureka/AsyncHealthCheckInvocationStrategyTest.java

Re-implement AsyncHealthCheckInvokationStrategy to provide more consistent delays when health check is invoked from multiple threads.

Improved AsyncHealthCheckInvokationStrategy

---

karyon2-admin-plugins/karyon-admin-healthcheck-plugin/build.gradle

jersey mixed versions caused test breaks

fixing transitive deps issue with jersey family

---

gradle.properties
karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/SimpleHttpServer.java
karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/rest/AdminServerConfig.java
karyon3-core/src/main/java/com/netflix/karyon/Karyon.java
karyon3-core/src/main/java/com/netflix/karyon/KaryonAutoContext.java
karyon3-core/src/main/java/com/netflix/karyon/LifecycleInjectorCreator.java
karyon3-core/src/main/java/com/netflix/karyon/LifecycleModule.java
karyon3-core/src/main/java/com/netflix/karyon/PostConstructLifecycleActions.java
karyon3-core/src/main/java/com/netflix/karyon/PreDestroyLifecycleActions.java
karyon3-core/src/main/java/com/netflix/karyon/spi/ModuleListTransformer.java
karyon3-eureka/src/main/java/com/netflix/karyon/eureka/EurekaApplicationAdminResource.java
karyon3-log4j2/build.gradle
karyon3-log4j2/src/main/java/com/netflix/karyon/log4j/ConsoleAppenderConfigurator.java

Introduce ModuleTransfomer as a mechanism to modify the final list of modules
Move move code from Governator to Karyon. Fixes shutdown bug

ModuleTransformer

---

karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/rest/AdminHttpHandler.java
karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/ui/AdminUIHttpHandler.java
karyon3-core/src/main/java/com/netflix/karyon/admin/CoreAdminModule.java
karyon3-core/src/main/java/com/netflix/karyon/admin/SystemInfoResource.java

Also add system-mbean admin resource

Fix resource leak in AdminHttpHandler and AdminUIHttpHandler

---

karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/FileSystemResourceProvider.java
karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/rest/AdminHttpHandler.java
karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/rest/AdminServerConfig.java
karyon3-admin-simple/src/main/java/com/netflix/karyon/admin/ui/AdminUIHttpHandler.java
karyon3-admin/src/main/resources/admin/index.js
karyon3-admin/src/main/resources/admin/sidebar.template
karyon3-core/src/main/java/com/netflix/karyon/admin/DIProvisionResource.java
karyon3-core/src/main/resources/admin/d3.flameGraph.css
karyon3-core/src/main/resources/admin/d3.flameGraph.js
karyon3-core/src/main/resources/admin/d3.tip.js
karyon3-core/src/main/resources/admin/di-graph.html
karyon3-core/src/main/resources/admin/di-graph.js
karyon3-core/src/main/resources/admin/di-provision.html
karyon3-core/src/main/resources/admin/di-provision.js

* Fix admin page header
* Fix di-privision resource

Misc admin UI fixes

---

karyon3-rxnetty/src/main/java/com/netflix/karyon/rxnetty/server/HttpRoutingRequestHandler.java

3.x Request logging at info level is too verbose in HttpRoutingRequestHandler

---

karyon2-admin-web/src/main/java/com/google/inject/grapher/KaryonAbstractInjectorGrapher.java
karyon2-admin-web/src/main/java/netflix/adminresources/pages/GuiceGraphPage.java
karyon2-admin-web/src/main/java/netflix/adminresources/pages/GuicePage.java
karyon2-admin-web/src/main/java/netflix/adminresources/pages/GuiceProvisionPage.java
karyon2-admin-web/src/main/java/netflix/adminresources/pages/KaryonGrapherModule.java
karyon2-admin-web/src/main/java/netflix/adminresources/resources/GuiceResource.java
karyon2-admin-web/src/main/java/netflix/adminresources/resources/JsonGrapher.java
karyon2-admin-web/src/main/resources/css/d3.flameGraph.css
karyon2-admin-web/src/main/resources/js/d3.flameGraph.js
karyon2-admin-web/src/main/resources/js/d3.tip.js
karyon2-admin-web/src/main/resources/webadmin/guice/index.ftl
karyon2-admin-web/src/main/resources/webadmin/guice/index.js
karyon2-admin-web/src/main/resources/webadmin/guicegraph/index.ftl
karyon2-admin-web/src/main/resources/webadmin/guicegraph/index.js
karyon2-admin-web/src/main/resources/webadmin/guiceprovision/index.ftl
karyon2-admin-web/src/main/resources/webadmin/guiceprovision/index.js
karyon2-admin-web/src/main/resources/webadmin/home.ftl
karyon2-admin/build.gradle
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesFilter.java
karyon2-admin/src/test/resources/log4j.properties

Add admin pages for Guice to
1.  Show all bound keys
2.  Flame graph to show allocation times
3.  Directed graph visualization of all bindings
Extension to AdminResourceContainers to serve static content in webjars

Admin pages for Guice

---

karyon2-admin-web/src/main/java/netflix/adminresources/resources/EnvironmentResource.java
karyon2-admin-web/src/main/java/netflix/adminresources/resources/jmx/DynaTreeNode.java
karyon2-admin/src/main/java/netflix/adminresources/KaryonAdminModule.java
karyon2-admin/src/test/java/netflix/adminresources/AdminResourceTest.java

focus of PR is to add guice binding to the server port of the AdminResourcesContainer (the embedded jetty admin server), but also removed some wayward tab characters found in two other classes

add guice binding for adminResourcesServerPort

---

karyon2-admin-web/src/main/java/netflix/adminresources/pages/AdminPageResource.java
karyon2-admin/src/main/java/netflix/admin/AdminFreemarkerTemplateProvider.java

added freemarker templateLoader that tries fetching the template via the AdminPageInfo's classloader.  If not available, it falls through to the current behavior of fetching the template from the AdminFreemarkerTemplateProvider's classloader

added support for resource loading from other class loaders

---

karyon2-admin/src/main/java/netflix/admin/AdminConfigImpl.java
karyon2-admin/src/main/java/netflix/admin/AdminContainerConfig.java
karyon2-admin/src/main/java/netflix/adminresources/AdminResourcesContainer.java

Allows for standing up an extra SSL-enabled port. (Let me know if there's a better way to go about this, but this seemed to fit into the existing configuration paradigm pretty well.)

Add configuration option to add additional connectors
